MOTION_TOKEN = "<M{:04}>"

ACTIVITY_LABELS = [
    "answer",
    "carry",
    "check",
    "clean",
    "close",
    "cook",
    "cut",
    "drag",
    "draw",
    "drink",
    "eat",
    "empty",
    "erase",
    "exit",
    "fill",
    "hold",
    "jump",
    "kneel",
    "kick",
    "lean",
    "lie",
    "lift",
    "make",
    "move",
    "open",
    "pack",
    "paint",
    "phone",
    "pick",
    "point",
    "press",
    "pull",
    "push",
    "put",
    "read",
    "remove",
    "run",
    "sit",
    "slide",
    "squat",
    "stand",
    "stand up",
    "step",
    "stir",
    "stop",
    "swing",
    "tap",
    "take",
    "talk",
    "text",
    "throw",
    "tie",
    "toast",
    "turn",
    "type",
    "use",
    "walk",
    "wash",
    "watch",
    "wave",
    "wear",
    "wipe",
]

JOINT_INDICES = {
    'pelvis': 0,
    'left_hip': 1,
    'right_hip': 2,
    'lower_spine': 3,
    'left_knee': 4,
    'right_knee': 5,
    'middle_spine': 6,
    'left_ankle': 7,
    'right_ankle': 8,
    'upper_spine': 9,
    'left_foot': 10,
    'right_foot': 11,
    'neck': 12,
    'left_collar': 13,
    'right_collar': 14,
    'head': 15,
    'left_shoulder': 16,
    'right_shoulder': 17,
    'left_elbow': 18,
    'right_elbow': 19,
    'left_wrist': 20,
    'right_wrist': 21,
}

POS_LABELS = {
    "at": 0,
    "facing towards": 1,
    "under": 2,
    "facing away": 3,
    "between": 4,
    "besides": 5,
    "right": 6,
    "left": 7,
}